### ISSUE TITLE
Borrow materials?

### ISSUE THREAD

**Issue by ttimbers** [theavanrossum/debuggerRMarkdownLesson#1]
@theavanrossum can I borrow/derive from these materials for teaching at UBC? If so, how do you want me to attribute? Thanks!

**Comment by ttimbers** [comment]
@theavanrossum any word whether we can use these or not?

**Comment by theavanrossum** [comment]
Woops missed this - thanks for the prompt. Yes you're absolutely welcome to them. Please also cite the RStudio tutorial I adapted it from - linked at the bottom.

**Comment by ttimbers** [comment]
Thanks Thea!

**Comment by ttimbers** [comment]
Thanks Thea!
